spring.application.name=pulse

jwt.secret=${JWT_SECRET:211e4129e577d9ea9dd8121745a497c6e62d4416f8186cfe7179cf29b4cb2fe3}
jwt.access-token-expiration-minutes=15
jwt.refresh-token-expiration-days=30

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:pulse}
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver
