spring.application.name=pulse

spring.datasource.url=jdbc:postgresql://localhost:5432/training
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

jwt.secret=211e4129e577d9ea9dd8121745a497c6e62d4416f8186cfe7179cf29b4cb2fe3
jwt.access-token-expiration-minutes=15
jwt.refresh-token-expiration-days=30

logging.level.com.pulse=INFO
